### ISSUE TITLE
FRP: Clean css

### ISSUE THREAD

**Issue by Majorfi** [yearn/web-lib#126]
In various places, the CSS used is kind of wild. We should try to replace the css attribution from tailwind inline classes to custom classes when possible, making it easier to customize components when required.
No absolute rule on that, we may have 3 property in one class with no specific need to create a custom class, but in general this should be done.

All custom classNames should be in this format:
`yearn--componentName-subComponentName`

All custom classNames should be wrapped in root:
```css
:root {
    .yearn--componentName-subComponentName {
        @apply something;
        display: flex;
    }
}
:root.dark {
 /* Only if a class need special support for dark mode. Just add the overrides*/
}
```
